
GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users/64405f6f1753ae4f9f9401c9

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "usuariochato3@gmail.com",
    "name": "Usuário Chato 4"
}

###

DELETE http://localhost:8080/api/users/6440637b8d62e3e6d3552ce2

###

PATCH http://localhost:8080/api/users/644063a28d62e3e6d3552ce8
Content-Type: application/json

{
    "name": "Usuário Chato 3"
}

###


