
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQwODhmMGJmNzM2OTQ2NmZjZjEzYmMiLCJuYW1lIjoicmV2aXN0YSIsImxhc3ROYW1lIjoibWFydGUiLCJlbWFpbCI6InJldmlzdGFtYXJ0ZWNvbnRhdG9AZ21haWwuY29tIiwicHJvbm91bnMiOiJub25lIiwic3Vic2NyaXB0aW9uIjoiZnJlZSIsIm1lbWJlclNpbmNlIjoiMjAyMy0wNC0yMFQwMDozNjowMC41NTRaIiwiX192IjowLCJpYXQiOjE2ODE5NjMzOTcsImV4cCI6MTY4MTk2MzQ1N30.r_CDcDozAVNYauXfH3u5DiiBW2dBheSk5r3wsrODoD4

###

GET http://localhost:8080/api/users/644088f0bf7369466fcf13bc


###

DELETE http://localhost:8080/api/users/6440837c2263b81327745048

###

PATCH http://localhost:8080/api/users/644063a28d62e3e6d3552ce8
Content-Type: application/json

{
    "name": "Usuário Chato 3"
}

###


